site_name: olas
repo_name: jorgeperezg/olas
repo_url: https://github.com/jorgeperezg/olas

theme:
  name: "material"
  logo: "art/logo_small.png"
  favicon: "art/logo_small.png"
  palette: 
    primary: "indigo"
    accent: "pink"
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.blocks.tab:
      alternate_style: True
  - pymdownx.blocks.admonition

nav:
  - index.md
